name: Lint

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install ruff black

            - name: Lint with ruff
              run: |
                  ruff check .

            - name: Check formatting with ruff
              run: |
                  ruff format --check .

            - name: Check formatting with black (fallback)
              run: |
                  black --check .
